Tracking Bitcoin Price
psybers/actual-helpers pull request #5
Opened 2024-08-20 18:38 UTC by Azelphur

Hi,

I wrote this primarily for myself, but I figured I'd clean it up a bit, perhaps others could make use of it. It allows you to put a note on the account in the format BTC:x (eg BTC:0.01) and it will create transactions to keep that accounts balance correct to the amount of BTC you have.

2024-08-20 20:04 UTC, psybers requested changes
Great, thank you for this!

2024-08-20 20:04 UTC, psybers commented on sync-bitcoin.js
> +  }
Do this after getting the bc price (so if that fails, the budget file was not opened).

```suggestion
  const bitcoinPrice = await getBitcoinPrice();
  if (!bitcoinPrice) {
    throw new Error("Unable to retrieve Bitcoin price. Check your BITCOIN_PRICE_URL and BITCOIN_PRICE_JSON_PATH environment variables");
  }
  await openBudget();
```

2024-08-20 20:04 UTC, psybers commented on sync-bitcoin.js
> +    response = await fetch(url);
Response can be defined below.

```suggestion
  const url = process.env.BITCOIN_PRICE_URL || "https://api.kraken.com/0/public/Ticker?pair=xbtusd"
  const path = process.env.BITCOIN_PRICE_JSON_PATH || "result.XXBTZUSD.c[0]"
  try {
    const response = await fetch(url);
```

2024-08-20 20:04 UTC, psybers commented on README.md
> +You can optionally change the API endpoint used to retrieve the Bitcoin price, an example for retrieving the price in GBP is `BITCOIN_PRICE_URL="https://api.kraken.com/0/public/Ticker?pair=xbtgbp"` `
Please wrap at column 80.

2024-08-20 20:04 UTC, psybers commented on README.md
> +### Tracking the Bitcoin Price
Be sure to add a link in the TOC above (around line 13).

2024-08-21 15:07 UTC, Azelphur commented
Thanks for the feedback, all good suggestions :) I believe I've corrected them all now.

2024-08-21 16:49 UTC, psybers approved these changes

2024-08-21 16:49 UTC, merged